#!/bin/sh
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"
# SCRAM verifier generated on the server; password travels only over stdin.
# Dollar-quoted random URL-safe secret generated by enterprise-init.py.
SECRET=$(cat deploy/secrets/replication_password)
case "$SECRET" in *[!A-Za-z0-9_-]*|'') echo 'Invalid generated replication secret' >&2; exit 2 ;; esac
docker compose --env-file .deploy.env exec -T db psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='promptlogic_replica') THEN CREATE ROLE promptlogic_replica LOGIN REPLICATION NOSUPERUSER NOCREATEDB NOCREATEROLE; END IF; END \$\$;
ALTER ROLE promptlogic_replica PASSWORD '$SECRET';
SQL
docker compose --env-file .deploy.env exec -T db sh -c 'line="host replication promptlogic_replica all scram-sha-256"; grep -qxF "$line" "$PGDATA/pg_hba.conf" || printf "\n%s\n" "$line" >> "$PGDATA/pg_hba.conf"'
docker compose --env-file .deploy.env -f docker-compose.yml -f docker-compose.replica.yml up -d db
# Allow primary restart to complete before taking the base backup.
docker compose --env-file .deploy.env -f docker-compose.yml -f docker-compose.replica.yml up -d --wait --wait-timeout 180 secondary
