"""Phase 1 authentication entitlements and prompt storage

Revision ID: 54d33aa80060
Revises:
Create Date: 2026-10-04 15:57:39.491422

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "54d33aa80060"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_buckets",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("count > 0", name=op.f("ck_rate_limit_buckets_positive_count")),
        sa.PrimaryKeyConstraint("key", "window_start", name=op.f("pk_rate_limit_buckets")),
    )
    with op.batch_alter_table("rate_limit_buckets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rate_limit_buckets_expires_at"), ["expires_at"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "entitlements",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plan_tier", sa.String(length=16), server_default="free", nullable=False),
        sa.Column("daily_ai_limit", sa.Integer(), server_default="10", nullable=False),
        sa.Column("razorpay_customer_id", sa.String(length=100), nullable=True),
        sa.Column("razorpay_subscription_id", sa.String(length=100), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("plan_tier IN ('free', 'pro')", name=op.f("ck_entitlements_plan_tier")),
        sa.CheckConstraint("daily_ai_limit > 0", name=op.f("ck_entitlements_positive_limit")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_entitlements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_entitlements")),
        sa.UniqueConstraint(
            "razorpay_customer_id", name=op.f("uq_entitlements_razorpay_customer_id")
        ),
        sa.UniqueConstraint(
            "razorpay_subscription_id", name=op.f("uq_entitlements_razorpay_subscription_id")
        ),
    )
    op.create_table(
        "extension_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=80), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_extension_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extension_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_extension_tokens_token_hash")),
    )
    with op.batch_alter_table("extension_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extension_tokens_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_extension_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "oauth_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('google', 'microsoft')", name=op.f("ck_oauth_identities_provider")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_identities")),
        sa.UniqueConstraint(
            "provider", "issuer", "subject", name=op.f("uq_oauth_identities_provider")
        ),
        sa.UniqueConstraint("user_id", "provider", name=op.f("uq_oauth_identities_user_id")),
    )
    with op.batch_alter_table("oauth_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_identities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "pairing_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("device_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pairing_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pairing_requests")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_pairing_requests_code_hash")),
    )
    with op.batch_alter_table("pairing_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pairing_requests_expires_at"), ["expires_at"], unique=False
        )

    op.create_table(
        "saved_prompts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=50)), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(content) BETWEEN 1 AND 50000", name=op.f("ck_saved_prompts_content_length")
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 200", name=op.f("ck_saved_prompts_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_prompts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_prompts")),
    )
    with op.batch_alter_table("saved_prompts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_saved_prompts_tags", ["tags"], unique=False, postgresql_using="gin"
        )
        batch_op.create_index(
            "ix_saved_prompts_user_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "usage_ledger",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ai_requests_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "ai_requests_count >= 0", name=op.f("ck_usage_ledger_nonnegative_count")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_ledger_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "date", name=op.f("pk_usage_ledger")),
    )
    op.create_table(
        "web_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_web_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_sessions")),
    )
    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_web_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_web_sessions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_web_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_web_sessions_expires_at"))

    op.drop_table("web_sessions")
    op.drop_table("usage_ledger")
    with op.batch_alter_table("saved_prompts", schema=None) as batch_op:
        batch_op.drop_index("ix_saved_prompts_user_created")
        batch_op.drop_index("ix_saved_prompts_tags", postgresql_using="gin")

    op.drop_table("saved_prompts")
    with op.batch_alter_table("pairing_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pairing_requests_expires_at"))

    op.drop_table("pairing_requests")
    with op.batch_alter_table("oauth_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_identities_user_id"))

    op.drop_table("oauth_identities")
    with op.batch_alter_table("extension_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extension_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_extension_tokens_expires_at"))

    op.drop_table("extension_tokens")
    op.drop_table("entitlements")
    op.drop_table("users")
    with op.batch_alter_table("rate_limit_buckets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rate_limit_buckets_expires_at"))

    op.drop_table("rate_limit_buckets")
    # ### end Alembic commands ###
