"""Phase 2 content free generation metrics

Revision ID: b65352810b54
Revises: 54d33aa80060
Create Date: 2026-10-04 16:24:24.647994

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b65352810b54"
down_revision = "54d33aa80060"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("preset_id", sa.String(length=40), nullable=False),
        sa.Column("preset_version", sa.String(length=40), nullable=False),
        sa.Column("engine", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("tone", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("tokenizer", sa.String(length=40), nullable=False),
        sa.Column("raw_tokens", sa.Integer(), nullable=False),
        sa.Column("generated_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "token_difference",
            sa.Integer(),
            sa.Computed("raw_tokens - generated_tokens", persisted=True),
            nullable=False,
        ),
        sa.Column("provider_input_tokens", sa.Integer(), nullable=True),
        sa.Column("provider_output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("engine IN ('ai', 'local')", name=op.f("ck_generation_metrics_engine")),
        sa.CheckConstraint("mode IN ('Build', 'Compact')", name=op.f("ck_generation_metrics_mode")),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_generation_metrics_latency")),
        sa.CheckConstraint(
            "provider_input_tokens IS NULL OR provider_input_tokens >= 0",
            name=op.f("ck_generation_metrics_input_tokens"),
        ),
        sa.CheckConstraint(
            "provider_output_tokens IS NULL OR provider_output_tokens >= 0",
            name=op.f("ck_generation_metrics_output_tokens"),
        ),
        sa.CheckConstraint(
            "raw_tokens > 0 AND generated_tokens > 0",
            name=op.f("ck_generation_metrics_positive_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_generation_metrics_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_metrics")),
    )
    with op.batch_alter_table("generation_metrics", schema=None) as batch_op:
        batch_op.create_index(
            "ix_generation_metrics_user_created", ["user_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generation_metrics", schema=None) as batch_op:
        batch_op.drop_index("ix_generation_metrics_user_created")

    op.drop_table("generation_metrics")
    # ### end Alembic commands ###
