"""Enterprise roles teams MFA rewards telemetry and consent dataset

Revision ID: df8c3dd9a82b
Revises: e02df4a6f04c
Create Date: 2026-10-06 09:31:37.005242

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "df8c3dd9a82b"
down_revision = "e02df4a6f04c"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("SET LOCAL lock_timeout = '5s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_request_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route", sa.String(length=120), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("provider_latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status BETWEEN 100 AND 599 AND latency_ms >= 0",
            name=op.f("ck_api_request_metrics_metric_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_request_metrics")),
    )
    with op.batch_alter_table("api_request_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_request_metrics_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "mail_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_outbox")),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)

    op.create_table(
        "coupons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("discount_type", sa.String(length=20), nullable=False),
        sa.Column("discount_value", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("current_uses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("days_granted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("razorpay_plan_id", sa.String(length=100), nullable=True),
        sa.Column("amount_paise", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_admin_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(discount_type='days_extension' AND days_granted>0 AND discount_value=0) OR "
            "(discount_type='percentage' AND discount_value BETWEEN 1 AND 99 AND "
            "razorpay_plan_id IS NOT NULL AND amount_paise>0) OR "
            "(discount_type='fixed_amount' AND discount_value>0 AND "
            "razorpay_plan_id IS NOT NULL AND amount_paise>0)",
            name=op.f("ck_coupons_coupon_value"),
        ),
        sa.CheckConstraint(
            "discount_type IN ('days_extension','percentage','fixed_amount')",
            name=op.f("ck_coupons_discount_type"),
        ),
        sa.CheckConstraint("days_granted BETWEEN 0 AND 365", name=op.f("ck_coupons_coupon_days")),
        sa.CheckConstraint(
            "max_uses > 0 AND current_uses BETWEEN 0 AND max_uses",
            name=op.f("ck_coupons_coupon_uses"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"],
            ["users.id"],
            name=op.f("fk_coupons_created_by_admin_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
        sa.UniqueConstraint("code", name=op.f("uq_coupons_code")),
    )
    op.create_table(
        "dataset_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("consent_version", sa.Integer(), nullable=False),
        sa.Column("encrypted_payload", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dataset_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_jobs")),
    )
    with op.batch_alter_table("dataset_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dataset_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "dataset_prompt_logs",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("preset_key", sa.String(length=80), nullable=False),
        sa.Column("raw_input_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("final_prompt_output", sa.Text(), nullable=False),
        sa.Column("model_response", sa.Text(), nullable=False),
        sa.Column("token_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality_rating", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_rating IS NULL OR quality_rating BETWEEN 1 AND 5",
            name=op.f("ck_dataset_prompt_logs_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dataset_prompt_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_dataset_prompt_logs")),
    )
    with op.batch_alter_table("dataset_prompt_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_prompt_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dataset_prompt_logs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "referral_balances",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("registration_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("conversion_days", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "registration_days BETWEEN 0 AND 30 AND conversion_days BETWEEN 0 AND 50",
            name=op.f("ck_referral_balances_reward_caps"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_referral_balances_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_referral_balances")),
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_id", sa.UUID(), nullable=False),
        sa.Column("referee_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("blocked_reason", sa.String(length=80), nullable=True),
        sa.Column("registration_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("conversion_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','registered','converted')",
            name=op.f("ck_referrals_referral_status"),
        ),
        sa.CheckConstraint("referrer_id <> referee_id", name=op.f("ck_referrals_no_self_referral")),
        sa.CheckConstraint(
            "registration_days BETWEEN 0 AND 3 AND conversion_days BETWEEN 0 AND 10",
            name=op.f("ck_referrals_referral_days"),
        ),
        sa.ForeignKeyConstraint(
            ["referee_id"],
            ["users.id"],
            name=op.f("fk_referrals_referee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.id"],
            name=op.f("fk_referrals_referrer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referrals")),
        sa.UniqueConstraint("referee_id", name=op.f("uq_referrals_referee_id")),
    )
    with op.batch_alter_table("referrals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_referrals_referrer_id"), ["referrer_id"], unique=False)

    op.create_table(
        "team_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="MEMBER", nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('ADMIN','MEMBER')", name=op.f("ck_team_invitations_role")),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_invitations_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_team_invitations_token_hash")),
    )
    with op.batch_alter_table("team_invitations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_invitations_team_id"), ["team_id"], unique=False)

    op.create_table(
        "team_memberships",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="MEMBER", nullable=False),
        sa.CheckConstraint(
            "role IN ('OWNER','ADMIN','MEMBER')", name=op.f("ck_team_memberships_role")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_memberships_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_team_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id", name=op.f("pk_team_memberships")),
    )
    with op.batch_alter_table("team_memberships", schema=None) as batch_op:
        batch_op.create_index("ix_membership_user", ["user_id"], unique=False)
        batch_op.create_index(
            "uq_team_owner", ["team_id"], unique=True, postgresql_where=sa.text("role='OWNER'")
        )

    op.create_table(
        "coupon_redemptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("coupon_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupons.id"],
            name=op.f("fk_coupon_redemptions_coupon_id_coupons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["billing_subscriptions.id"],
            name=op.f("fk_coupon_redemptions_subscription_id_billing_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_coupon_redemptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_redemptions")),
        sa.UniqueConstraint("coupon_id", "user_id", name=op.f("uq_coupon_redemptions_coupon_id")),
        sa.UniqueConstraint("subscription_id", name=op.f("uq_coupon_redemptions_subscription_id")),
    )
    with op.batch_alter_table("coupon_redemptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_coupon_redemptions_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("custom_presets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f("ix_custom_presets_team_id"), ["team_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_custom_presets_team_id_teams"),
            "teams",
            ["team_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("entitlements", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("bonus_expires_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("override_tier", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("override_limit", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("override_expires_at", sa.DateTime(timezone=True), nullable=True)
        )

    with op.batch_alter_table("saved_prompts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f("ix_saved_prompts_team_id"), ["team_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_saved_prompts_team_id_teams"),
            "teams",
            ["team_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False)
        )
        batch_op.add_column(sa.Column("totp_secret", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("totp_enabled", sa.Boolean(), server_default="false", nullable=False)
        )
        batch_op.add_column(
            sa.Column("totp_last_step", sa.BigInteger(), server_default="-1", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "recovery_hashes",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default="[]",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("dataset_consent", sa.Boolean(), server_default="false", nullable=False)
        )
        batch_op.add_column(
            sa.Column("consent_version", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("referral_code", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("ip_hash", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("device_hash", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("payment_hash", sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_users_referral_code"), ["referral_code"])

    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mfa_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

    op.create_check_constraint(
        op.f("ck_entitlements_override_tier"),
        "entitlements",
        "override_tier IS NULL OR override_tier IN ('free','pro')",
    )
    op.create_check_constraint(
        op.f("ck_entitlements_override_limit"),
        "entitlements",
        "override_limit IS NULL OR override_limit BETWEEN 1 AND 10000",
    )

    op.execute("""
        CREATE FUNCTION promptlogic_audit_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'Audit records are append-only'; END $$;
        CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION promptlogic_audit_immutable();
    """)


def downgrade():
    op.execute("DROP TRIGGER IF EXISTS audit_immutable ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS promptlogic_audit_immutable()")
    op.drop_constraint(op.f("ck_entitlements_override_limit"), "entitlements", type_="check")
    op.drop_constraint(op.f("ck_entitlements_override_tier"), "entitlements", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.drop_column("mfa_at")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_referral_code"), type_="unique")
        batch_op.drop_column("payment_hash")
        batch_op.drop_column("device_hash")
        batch_op.drop_column("ip_hash")
        batch_op.drop_column("referral_code")
        batch_op.drop_column("consent_version")
        batch_op.drop_column("dataset_consent")
        batch_op.drop_column("recovery_hashes")
        batch_op.drop_column("totp_last_step")
        batch_op.drop_column("totp_enabled")
        batch_op.drop_column("totp_secret")
        batch_op.drop_column("is_admin")

    with op.batch_alter_table("saved_prompts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_saved_prompts_team_id_teams"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_saved_prompts_team_id"))
        batch_op.drop_column("team_id")

    with op.batch_alter_table("entitlements", schema=None) as batch_op:
        batch_op.drop_column("override_expires_at")
        batch_op.drop_column("override_limit")
        batch_op.drop_column("override_tier")
        batch_op.drop_column("bonus_expires_at")

    with op.batch_alter_table("custom_presets", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_custom_presets_team_id_teams"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_custom_presets_team_id"))
        batch_op.drop_column("team_id")

    with op.batch_alter_table("coupon_redemptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_coupon_redemptions_user_id"))

    op.drop_table("coupon_redemptions")
    with op.batch_alter_table("team_memberships", schema=None) as batch_op:
        batch_op.drop_index("uq_team_owner", postgresql_where=sa.text("role='OWNER'"))
        batch_op.drop_index("ix_membership_user")

    op.drop_table("team_memberships")
    with op.batch_alter_table("team_invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_invitations_team_id"))

    op.drop_table("team_invitations")
    with op.batch_alter_table("referrals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_referrals_referrer_id"))

    op.drop_table("referrals")
    op.drop_table("referral_balances")
    with op.batch_alter_table("dataset_prompt_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_prompt_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_dataset_prompt_logs_created_at"))

    op.drop_table("dataset_prompt_logs")
    with op.batch_alter_table("dataset_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_jobs_user_id"))

    op.drop_table("dataset_jobs")
    op.drop_table("coupons")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))

    op.drop_table("audit_logs")
    op.drop_table("teams")
    op.drop_table("mail_outbox")
    with op.batch_alter_table("api_request_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_request_metrics_created_at"))

    op.drop_table("api_request_metrics")
    # ### end Alembic commands ###
