"""Phase 3 billing subscriptions webhooks and custom presets

Revision ID: e02df4a6f04c
Revises: b65352810b54
Create Date: 2026-10-04 17:00:26.771023

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e02df4a6f04c"
down_revision = "b65352810b54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_webhooks",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("subscription_id", sa.String(length=100), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_billing_webhooks")),
        sa.UniqueConstraint("payload_hash", name=op.f("uq_billing_webhooks_payload_hash")),
    )
    op.create_table(
        "billing_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("razorpay_id", sa.String(length=100), nullable=True),
        sa.Column("plan_id", sa.String(length=100), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="creating", nullable=False),
        sa.Column("checkout_url", sa.String(length=500), nullable=True),
        sa.Column("current_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_event_at", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("cancel_at_cycle_end", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_billing_subscriptions_currency")),
        sa.CheckConstraint(
            "status IN ('creating','uncertain','failed','created','authenticated',"
            "'active','pending','halted','cancelled','completed','expired')",
            name=op.f("ck_billing_subscriptions_status"),
        ),
        sa.CheckConstraint(
            "amount_paise > 0", name=op.f("ck_billing_subscriptions_positive_amount")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_billing_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_subscriptions")),
        sa.UniqueConstraint("razorpay_id", name=op.f("uq_billing_subscriptions_razorpay_id")),
    )
    with op.batch_alter_table("billing_subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_billing_subscriptions_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "uq_billing_subscriptions_open_user",
            ["user_id"],
            unique=True,
            postgresql_where=sa.text(
                "status IN ('creating','uncertain','created','authenticated',"
                "'active','pending','halted')"
            ),
        )

    op.create_table(
        "custom_presets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=200), nullable=False),
        sa.Column("required_fields", sa.JSON(), nullable=False),
        sa.Column("optional_fields", sa.JSON(), nullable=False),
        sa.Column("output_constraints", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_custom_presets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_presets")),
    )
    with op.batch_alter_table("custom_presets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_custom_presets_user_id"), ["user_id"], unique=False)

    op.create_table(
        "billing_payments",
        sa.Column("payment_id", sa.String(length=100), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["billing_subscriptions.id"],
            name=op.f("fk_billing_payments_subscription_id_billing_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("payment_id", name=op.f("pk_billing_payments")),
    )
    with op.batch_alter_table("billing_payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_billing_payments_subscription_id"), ["subscription_id"], unique=False
        )

    with op.batch_alter_table("generation_metrics", schema=None) as batch_op:
        batch_op.alter_column(
            "preset_id",
            existing_type=sa.VARCHAR(length=40),
            type_=sa.String(length=80),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # Retain numeric history when removing custom presets; their UUID labels exceed Phase 2's width.
    op.execute(
        "UPDATE generation_metrics SET preset_id = 'custom_archived' "
        "WHERE char_length(preset_id) > 40"
    )
    with op.batch_alter_table("generation_metrics", schema=None) as batch_op:
        batch_op.alter_column(
            "preset_id",
            existing_type=sa.String(length=80),
            type_=sa.VARCHAR(length=40),
            existing_nullable=False,
        )

    with op.batch_alter_table("billing_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_billing_payments_subscription_id"))

    op.drop_table("billing_payments")
    with op.batch_alter_table("custom_presets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_custom_presets_user_id"))

    op.drop_table("custom_presets")
    with op.batch_alter_table("billing_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_billing_subscriptions_open_user",
            postgresql_where=sa.text(
                "status IN ('creating','uncertain','created','authenticated',"
                "'active','pending','halted')"
            ),
        )
        batch_op.drop_index("ix_billing_subscriptions_user_created")

    op.drop_table("billing_subscriptions")
    op.drop_table("billing_webhooks")
    # ### end Alembic commands ###
